spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ms
    username: user
    password: 123
    driver-class-name: org.postgresql.Driver

# Configurações do Hibernate
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.PostgreSQLDialect

# Configuração do Eureka Client
eureka:
  client:
    service-url:
      default-zone: http://eureka-server:8761/eureka/
